### ISSUE TITLE
Buslines not spawning buses.

### ISSUE THREAD

**Issue by Henchgirls** [klyte45/TransportLinesManager#151]
As of the lastest steam version, all bus depots seem to refuse to spawn buses to buslines. I've tested with both the biofuel bus and the regular bus. None of the two lines drawn out on the map have been populated at all.

**Comment by klyte45** [comment]
It seems to be something related to TM:PE or a corrupted asset.
I suggest to send this log for TM:PE team to them check it out. I found just this as an issue related to vehicle spawning:
```

Vehicle not found!
   at System.Environment.get_StackTrace()
   at Building.RemoveOwnVehicle(UInt16 vehicleID, Vehicle ByRef data)
   at FireTruckAI.RemoveSource(UInt16 vehicleID, Vehicle ByRef data)
   at FireTruckAI.ArriveAtSource(UInt16 vehicleID, Vehicle ByRef data)
   at FireTruckAI.ArriveAtDestination(UInt16 vehicleID, Vehicle ByRef vehicleData)
   at CarAI.CarAI.SimulationStep_Patch0(.CarAI , UInt16 , Vehicle ByRef , Frame ByRef , UInt16 , Vehicle ByRef , Int32 )
   at FireTruckAI.SimulationStep(UInt16 vehicleID, Vehicle ByRef vehicleData, Frame ByRef frameData, UInt16 leaderID, Vehicle ByRef leaderData, Int32 lodPhysics)
   at VehicleAI.VehicleAI.SimulationStep_Patch1(.VehicleAI , UInt16 , Vehicle ByRef , UInt16 , Vehicle ByRef , Int32 )
   at TrafficManager.Custom.AI.CustomCarAI.CustomSimulationStep(UInt16 vehicleId, Vehicle ByRef vehicleData, Vector3 physicsLodRefPos)
   at FireTruckAI.SimulationStep(UInt16 vehicleID, Vehicle ByRef data, Vector3 physicsLodRefPos)
   at VehicleManager.SimulationStepImpl(Int32 subStep)
   at SimulationManagerBase`2.SimulationStep(Int32 subStep)
   at VehicleManager.ISimulationManager.SimulationStep(Int32 subStep)
   at SimulationManager.SimulationStep()
   at SimulationManager.SimulationThread()  [Core]
   ```
   
   Once there's no issue with TLM shown in the log by now, I will close this. Feel free to reopen if there's something new about this.
