### ISSUE TITLE
Game crash issues CTD 

### ISSUE THREAD

**Issue by a38090** [klyte45/TransportLinesManager#172]
Hello, i'm very love and continuing using your mod for quite a long time, but the last day patch, seems to lead to the CTD issues, which is the game crash.
I tried to deactivate your mod, the transportlines manager, and it successfully entered the game.
I ran a few scenarios to prove something whether have some point of conflict by myself
1. creat a new game, transportlines manger actived, still crashed
2. deactivate the AVO, still crashed.
When I turn to the output log,
some lines attract my interests, 

Scene [Ingame] loaded
TLMv14.2 Starting panel at version 20211014
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Cannot set relative position without a parent Transform.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

TLMv14.2 Trying to access controller while loading. NOT ALLOWED!
Ask at Klyte45's GitHub to fix this. Stacktrace:
   at System.Environment.get_StackTrace()
   at Klyte.Commons.Interfaces.BasicIUserModSimplified`2[[Klyte.TransportLinesManager.TransportLinesManagerMod, TransportLinesManager, Version=14.2.0.3, Culture=neutral, PublicKeyToken=null],[Klyte.TransportLinesManager.TLMController, TransportLinesManager, Version=14.2.0.3, Culture=neutral, PublicKeyToken=null]].get_Controller()
   at Klyte.TransportLinesManager.TLMController.get_Instance()
   at Klyte.TransportLinesManager.TLMController.get_IsRealTimeEnabled()
   at Klyte.TransportLinesManager.UI.TLMReportsTab.Start()
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

TLMv14.2 Trying to access controller while loading. NOT ALLOWED!
Ask at Klyte45's GitHub to fix this. Stacktrace:
   at System.Environment.get_StackTrace()
   at Klyte.Commons.Interfaces.BasicIUserModSimplified`2[[Klyte.TransportLinesManager.TransportLinesManagerMod, TransportLinesManager, Version=14.2.0.3, Culture=neutral, PublicKeyToken=null],[Klyte.TransportLinesManager.TLMController, TransportLinesManager, Version=14.2.0.3, Culture=neutral, PublicKeyToken=null]].get_Controller()
   at Klyte.TransportLinesManager.TLMController.get_Instance()
   at Klyte.TransportLinesManager.TLMController.VerifyIfIsRealTimeEnabled()
   at Klyte.TransportLinesManager.TLMController.get_IsRealTimeEnabled()
   at Klyte.TransportLinesManager.UI.TLMReportsTab.Start()
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

TLMv14.2 Trying to access controller while loading. NOT ALLOWED!
Ask at Klyte45's GitHub to fix this. Stacktrace:
   at System.Environment.get_StackTrace()
   at Klyte.Commons.Interfaces.BasicIUserModSimplified`2[[Klyte.TransportLinesManager.TransportLinesManagerMod, TransportLinesManager, Version=14.2.0.3, Culture=neutral, PublicKeyToken=null],[Klyte.TransportLinesManager.TLMController, TransportLinesManager, Version=14.2.0.3, Culture=neutral, PublicKeyToken=null]].get_Controller()
   at Klyte.TransportLinesManager.TLMController.get_Instance()
   at Klyte.TransportLinesManager.TLMController.get_IsRealTimeEnabled()
   at Klyte.TransportLinesManager.UI.TLMReportsTab.Start()
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

TLMv14.2 K45 PANEL REMOVED @    at System.Environment.get_StackTrace()
   at Klyte.Commons.Utils.K45DialogControl.OnDestroy()
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**and**
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Unknown prefab: Tornado  [Serialization]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Error with MAIN_CATEGORY[RoadsTiny]:0: The id was not found in the localization files.  [Localization - Internal]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

System.TypeInitializationException: An exception was thrown by the type initializer for Mono.CSharp.CSharpCodeCompiler ---> System.IO.FileNotFoundException: Windows mono path not found: C:\Program Files (x86)\Steam\steamapps\mono\mono\mini\mono.exe
  at Mono.CSharp.CSharpCodeCompiler..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Microsoft.CSharp.CSharpCodeProvider.CreateCompiler () [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.GenerateSerializers (System.Xml.Serialization.GenerationBatch batch, System.CodeDom.Compiler.CompilerParameters cp) [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.RunSerializerGeneration (System.Object obj) [0x00000] in <filename unknown>:0 
System.TypeInitializationException: An exception was thrown by the type initializer for Mono.CSharp.CSharpCodeCompiler ---> System.IO.FileNotFoundException: Windows mono path not found: C:\Program Files (x86)\Steam\steamapps\mono\mono\mini\mono.exe
  at Mono.CSharp.CSharpCodeCompiler..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Microsoft.CSharp.CSharpCodeProvider.CreateCompiler () [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.GenerateSerializers (System.Xml.Serialization.GenerationBatch batch, System.CodeDom.Compiler.CompilerParameters cp) [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.RunSerializerGeneration (System.Object obj) [0x00000] in <filename unknown>:0 
System.TypeInitializationException: An exception was thrown by the type initializer for Mono.CSharp.CSharpCodeCompiler ---> System.IO.FileNotFoundException: Windows mono path not found: C:\Program Files (x86)\Steam\steamapps\mono\mono\mini\mono.exe
  at Mono.CSharp.CSharpCodeCompiler..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Microsoft.CSharp.CSharpCodeProvider.CreateCompiler () [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.GenerateSerializers (System.Xml.Serialization.GenerationBatch batch, System.CodeDom.Compiler.CompilerParameters cp) [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.RunSerializerGeneration (System.Object obj) [0x00000] in <filename unknown>:0 
System.TypeInitializationException: An exception was thrown by the type initializer for Mono.CSharp.CSharpCodeCompiler ---> System.IO.FileNotFoundException: Windows mono path not found: C:\Program Files (x86)\Steam\steamapps\mono\mono\mini\mono.exe
  at Mono.CSharp.CSharpCodeCompiler..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Microsoft.CSharp.CSharpCodeProvider.CreateCompiler () [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.GenerateSerializers (System.Xml.Serialization.GenerationBatch batch, System.CodeDom.Compiler.CompilerParameters cp) [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.RunSerializerGeneration (System.Object obj) [0x00000] in <filename unknown>:0 
System.TypeInitializationException: An exception was thrown by the type initializer for Mono.CSharp.CSharpCodeCompiler ---> System.IO.FileNotFoundException: Windows mono path not found: C:\Program Files (x86)\Steam\steamapps\mono\mono\mini\mono.exe
  at Mono.CSharp.CSharpCodeCompiler..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Microsoft.CSharp.CSharpCodeProvider.CreateCompiler () [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.GenerateSerializers (System.Xml.Serialization.GenerationBatch batch, System.CodeDom.Compiler.CompilerParameters cp) [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.RunSerializerGeneration (System.Object obj) [0x00000] in <filename unknown>:0 
System.TypeInitializationException: An exception was thrown by the type initializer for Mono.CSharp.CSharpCodeCompiler ---> System.IO.FileNotFoundException: Windows mono path not found: C:\Program Files (x86)\Steam\steamapps\mono\mono\mini\mono.exe
  at Mono.CSharp.CSharpCodeCompiler..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Microsoft.CSharp.CSharpCodeProvider.CreateCompiler () [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.GenerateSerializers (System.Xml.Serialization.GenerationBatch batch, System.CodeDom.Compiler.CompilerParameters cp) [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.RunSerializerGeneration (System.Object obj) [0x00000] in <filename unknown>:0 
System.TypeInitializationException: An exception was thrown by the type initializer for Mono.CSharp.CSharpCodeCompiler ---> System.IO.FileNotFoundException: Windows mono path not found: C:\Program Files (x86)\Steam\steamapps\mono\mono\mini\mono.exe
  at Mono.CSharp.CSharpCodeCompiler..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Microsoft.CSharp.CSharpCodeProvider.CreateCompiler () [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.GenerateSerializers (System.Xml.Serialization.GenerationBatch batch, System.CodeDom.Compiler.CompilerParameters cp) [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.RunSerializerGeneration (System.Object obj) [0x00000] in <filename unknown>:0 
System.TypeInitializationException: An exception was thrown by the type initializer for Mono.CSharp.CSharpCodeCompiler ---> System.IO.FileNotFoundException: Windows mono path not found: C:\Program Files (x86)\Steam\steamapps\mono\mono\mini\mono.exe
  at Mono.CSharp.CSharpCodeCompiler..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Microsoft.CSharp.CSharpCodeProvider.CreateCompiler () [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.GenerateSerializers (System.Xml.Serialization.GenerationBatch batch, System.CodeDom.Compiler.CompilerParameters cp) [0x00000] in <filename unknown>:0 
  at System.Xml.Serialization.XmlSerializer.RunSerializerGeneration (System.Object obj) [0x00000] in <filename unknown>:0 
Colossal Handler caught: Could not find a part of the path "C:\Users\A380\AppData\Local\Temp\61c3b822\7c908207.cs".
  at System.IO.File.Delete (System.String path) [0x00000] in <filename unknown>:0 

  at System.CodeDom.Compiler.TempFileCollection.Delete () [0x00000] in <filename unknown>:0 

  at System.CodeDom.Compiler.TempFileCollection.Dispose (Boolean disposing) [0x00000] in <filename unknown>:0 

  at System.CodeDom.Compiler.TempFileCollection.Finalize () [0x00000] in <filename unknown>:0 
Runtime terminating: True
The game will now crash. Sorry for the inconvenience...
**SO**
could you be so kind as to see whether you can fix this issues?

**Comment by klyte45** [comment]
Well, the alert about `TLMv14.2 Trying to access controller while loading. NOT ALLOWED!` isn't something to worry about.
The `An exception was thrown by the type initializer for Mono.CSharp.CSharpCodeCompiler` will be solved in next patch (r4).

I will ask you to test after the update to check if this still happening. It will be updated in minutes

**Comment by a38090** [comment]
Hello,developer, I downloaded the latest update, but it still crashing CTD issues, and the output will not show" An exception was thrown by the type initializer for Mono.CSharp.CSharpCodeCompiler" again, but it still crashed
I uploaded the output and nevertheless you can see it in greater detail
[output_log.txt](https://github.com/klyte45/TransportLinesManager/files/7717523/output_log.txt)
.

**Comment by klyte45** [comment]
I did another version with a bugfix and it's already at workshop (r6)
Please give a try

**Comment by a38090** [comment]
Hello, developer, i upadted the latest version of the TLM, but it still crashed, i don't know the reason, the output logo is on the attach file.
[output_log.txt](https://github.com/klyte45/TransportLinesManager/files/7718144/output_log.txt)

**Comment by klyte45** [comment]
Please turn on the debug mod and try again
The debug mode option is under the mod tab at options menu

**Comment by a38090** [comment]
Ok I ran under the debug mode again and produced a new out put log at the attach file, please take a look, thanks
[output_log(debug mode enabled).txt](https://github.com/klyte45/TransportLinesManager/files/7718219/output_log.debug.mode.enabled.txt)
!

**Comment by klyte45** [comment]
Still having nothing related to my mod there, despite the last logging line being from TLM

My last try would be deactivating the Vehicles Effects mod, theres a lot of warnings from it here

**Comment by a38090** [comment]
Hello, i tried to disabled the vehicles effects mod, but it still crashing, maybe I should temporarily disabled the TLM and return to the orginal way, i believe it will reduce brothering you, and leave you to find something that can make it works at someday and release it as a pacth update.

**Comment by JumpJumpo** [comment]
Hi same problem for me.
The game will start only with deinstalling your mod. I'll try to submit a debug in a few.

Is there an asset conflict?

**Comment by Paputto0** [comment]
Dear @klyte45 ,
Thanks for your work - I truly appreciate it!

I have the same problem as everyone above - the symptoms are the same. I've attached the output_log, if you need anything more just let me know
[output_log.txt](https://github.com/klyte45/TransportLinesManager/files/7721181/output_log.txt)
.

**Comment by klyte45** [comment]
Guys, try to subscribe to this mod: https://steamcommunity.com/sharedfiles/filedetails/?id=2255219025
And try to load the game, it might be the source of the issue

**Comment by klyte45** [comment]
Well, I was able to reproduce the issue here, and the fix is being uploaded to workshop in the version r7
Thanks for the reports

**Comment by a38090** [comment]
Hello,developer, good news, the r7 will not have CTD issues, Thanks for your help!!
