### ISSUE TITLE
[BUG] Error while loading

### ISSUE THREAD

**Issue by sergjack2015** [klyte45/TransportLinesManager#196]
While loading the game, an error appears in the output log, but it doesnt seem to actually do anything in the game.

Error log:

883,803ms | TLMv14.2 Trying to access controller while loading. NOT ALLOWED!
Ask at Klyte45's GitHub to fix this. Stacktrace:
   at System.Environment.get_StackTrace()
   at Klyte.Commons.Interfaces.BasicIUserModSimplified`2[[Klyte.TransportLinesManager.TransportLinesManagerMod, TransportLinesManager, Version=14.2.0.9, Culture=neutral, PublicKeyToken=null],[Klyte.TransportLinesManager.TLMController, TransportLinesManager, Version=14.2.0.9, Culture=neutral, PublicKeyToken=null]].get_Controller()
   at Klyte.TransportLinesManager.TLMController.get_Instance()
   at Klyte.TransportLinesManager.TLMController.VerifyIfIsRealTimeEnabled()
   at Klyte.TransportLinesManager.TLMController.get_IsRealTimeEnabled()
   at Klyte.TransportLinesManager.UI.TLMReportsTab.Start()

**Comment by klyte45** [comment]
This is harmless. Just ignore
