### ISSUE TITLE
[BUG] Buses Not Spawning

### ISSUE THREAD

**Issue by FutureProg** [klyte45/TransportLinesManager#225]
**Describe the bug**
Whenever I create a bus line, the buses don't spawn for some reason. 

**To Reproduce**
I believe all I did was change a few of the bus line numbers and how they would be formatted. 

**Game Logs**
I notice this line in the logs: 
`TLMv14.3 Local TSD NOT FOUND FOR TRANSPORT INFO: info.m_class.m_subService=PublicTransportBus, info.m_vehicleType=Car, info.m_transportType=Bus, info.classLevel = Level3`
[output.txt](https://drive.google.com/file/d/1K2P_qU3UhCrTZPKX4godV53qK0ENe6ql/view?usp=sharing)

Another error I noticed:
`TLMv14.3 Index (Bus,PublicTransportBus,Car,Level1) == 00004A0F
   at System.Environment.get_StackTrace()
   at Klyte.TransportLinesManager.Extensions.TransportSystemDefinition.From(TransportType TransportType, SubService SubService, VehicleType VehicleType, Level Level)
   at Klyte.TransportLinesManager.Xml.TsdIdentifiable.get_TSD()
   at Klyte.TransportLinesManager.Extensions.TLMTransportTypeConfigurations.get_Definition()
   at Klyte.TransportLinesManager.Extensions.TLMTransportTypeConfigurations.LoadBasicAssets()
   at Klyte.TransportLinesManager.Extensions.TLMTransportTypeConfigurations.GetAllBasicAssetsForLine(UInt16 lineId)
   at Klyte.TransportLinesManager.UI.TLMAssetSelectorTab.UpdateAssetList(IBasicExtension config)
   at Klyte.TransportLinesManager.UI.TLMAssetSelectorTab.OnSetTarget(System.Type source)
   at Klyte.TransportLinesManager.UI.UVMPublicTransportWorldInfoPanel.OnSetTarget()
   at PublicTransportWorldInfoPanel.PublicTransportWorldInfoPanel.OnSetTarget_Patch1(.PublicTransportWorldInfoPanel )
   at WorldInfoPanel.SetTarget(Vector3 worldMousePosition, InstanceID id)
   at WorldInfoPanel.Show(Vector3 worldMousePosition, InstanceID instanceID)
   at Klyte.TransportLinesManager.CommonsWindow.UVMLineListItem.<Awake>b__53_2(ColossalFramework.UI.UIComponent c, ColossalFramework.UI.UIMouseEventParameter r)
   at ColossalFramework.UI.UIComponent.OnClick(ColossalFramework.UI.UIMouseEventParameter p)
   at ColossalFramework.UI.UIButton.OnClick(ColossalFramework.UI.UIMouseEventParameter p)
   at ColossalFramework.UI.UIInput+MouseHandler.ProcessInput(IInputTranslator translator, Ray ray, ColossalFramework.UI.UIComponent component, Boolean retainFocusSetting)
   at ColossalFramework.UI.UIInput.ProcessMouseInput()
   at ColossalFramework.UI.UIInput.Update()`

There are similar errors for other vehicle types. Just not trams.

**Comment by FutureProg** [comment]
I've updated with the debug output after adding another bus line which should be number 5.

**Comment by klyte45** [comment]
There's not wrong here. Level3 is intercity bus, not managed by TLM and is expected to not find a Local TSD, because it's regional.

The other stack is just informative, nothing wrong.
