### ISSUE TITLE
[BUG] Ask at Klyte45's GitHub to fix this.

### ISSUE THREAD

**Issue by t1a2l** [klyte45/TransportLinesManager#247]
Ask at Klyte45's GitHub to fix this. Stacktrace:
   at System.Environment.get_StackTrace()
   at Klyte.Commons.Interfaces.BasicIUserModSimplified`2[[Klyte.TransportLinesManager.TransportLinesManagerMod, TransportLinesManager, Version=14.3.0.0, Culture=neutral, PublicKeyToken=null],[Klyte.TransportLinesManager.TLMController, TransportLinesManager, Version=14.3.0.0, Culture=neutral, PublicKeyToken=null]].get_Controller()
   at Klyte.TransportLinesManager.ModShared.TLMFacade.get_Instance()
   at Klyte.TransportLinesManager.Extensions.OutsideConnectionLineInfo.set_LineBgSprite(LineIconSpriteNames value)
   at Klyte.TransportLinesManager.Extensions.OutsideConnectionLineInfo.set_LineBgForm(System.String value)
   at System.Reflection.MonoMethod.InternalInvoke(System.Object , System.Object[] , System.Exception ByRef )
   at System.Reflection.MonoMethod.Invoke(System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
   at System.Reflection.MonoProperty.SetValue(System.Object obj, System.Object value, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] index, System.Globalization.CultureInfo culture)
   at System.Reflection.PropertyInfo.SetValue(System.Object obj, System.Object value, System.Object[] index)
   at System.Xml.Serialization.XmlTypeMapMember.SetValue(System.Object ob, System.Object value)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.SetMemberValue(System.Xml.Serialization.XmlTypeMapMember member, System.Object ob, System.Object value, Boolean isValueList)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadAttributeMembers(System.Xml.Serialization.ClassMap map, System.Object ob, Boolean isValueList)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadMembers(System.Xml.Serialization.ClassMap map, System.Object ob, Boolean isValueList, Boolean readByOrder)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadClassInstanceMembers(System.Xml.Serialization.XmlTypeMapping typeMap, System.Object ob)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadClassInstance(System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadObject(System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadRoot(System.Xml.Serialization.XmlTypeMapping rootMap)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadRoot()
   at System.Xml.Serialization.XmlSerializer.Deserialize(System.Xml.Serialization.XmlSerializationReader reader)
   at System.Xml.Serialization.XmlSerializer.Deserialize(System.Xml.XmlReader xmlReader)
   at Klyte.Commons.Utils.NonSequentialList`1[[Klyte.TransportLinesManager.Extensions.OutsideConnectionLineInfo, TransportLinesManager, Version=14.3.0.0, Culture=neutral, PublicKeyToken=null]].ReadXml(System.Xml.XmlReader reader)
   at System.Xml.Serialization.XmlSerializationReader.ReadSerializable(IXmlSerializable serializable)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadObjectElement(System.Xml.Serialization.XmlTypeMapElementInfo elem)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadMembers(System.Xml.Serialization.ClassMap map, System.Object ob, Boolean isValueList, Boolean readByOrder)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadClassInstanceMembers(System.Xml.Serialization.XmlTypeMapping typeMap, System.Object ob)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadClassInstance(System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadObject(System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadRoot(System.Xml.Serialization.XmlTypeMapping rootMap)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadRoot()
   at System.Xml.Serialization.XmlSerializer.Deserialize(System.Xml.Serialization.XmlSerializationReader reader)
   at System.Xml.Serialization.XmlSerializer.Deserialize(System.Xml.XmlReader xmlReader)
   at Klyte.Commons.Utils.NonSequentialList`1[[Klyte.TransportLinesManager.Extensions.PlatformConfig, TransportLinesManager, Version=14.3.0.0, Culture=neutral, PublicKeyToken=null]].ReadXml(System.Xml.XmlReader reader)
   at System.Xml.Serialization.XmlSerializationReader.ReadSerializable(IXmlSerializable serializable)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadObjectElement(System.Xml.Serialization.XmlTypeMapElementInfo elem)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadMembers(System.Xml.Serialization.ClassMap map, System.Object ob, Boolean isValueList, Boolean readByOrder)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadClassInstanceMembers(System.Xml.Serialization.XmlTypeMapping typeMap, System.Object ob)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadClassInstance(System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadObject(System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadRoot(System.Xml.Serialization.XmlTypeMapping rootMap)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadRoot()
   at System.Xml.Serialization.XmlSerializer.Deserialize(System.Xml.Serialization.XmlSerializationReader reader)
   at System.Xml.Serialization.XmlSerializer.Deserialize(System.Xml.XmlReader xmlReader)
   at Klyte.Commons.Utils.NonSequentialList`1[[Klyte.TransportLinesManager.Extensions.TLMBuildingsConfiguration, TransportLinesManager, Version=14.3.0.0, Culture=neutral, PublicKeyToken=null]].ReadXml(System.Xml.XmlReader reader)
   at System.Xml.Serialization.XmlSerializationReader.ReadSerializable(IXmlSerializable serializable)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadObjectElement(System.Xml.Serialization.XmlTypeMapElementInfo elem)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadMembers(System.Xml.Serialization.ClassMap map, System.Object ob, Boolean isValueList, Boolean readByOrder)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadClassInstanceMembers(System.Xml.Serialization.XmlTypeMapping typeMap, System.Object ob)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadClassInstance(System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadObject(System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadRoot(System.Xml.Serialization.XmlTypeMapping rootMap)
   at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadRoot()
   at System.Xml.Serialization.XmlSerializer.Deserialize(System.Xml.Serialization.XmlSerializationReader reader)
   at System.Xml.Serialization.XmlSerializer.Deserialize(System.Xml.XmlReader xmlReader)
   at Klyte.Commons.Utils.XmlUtils.DefaultXmlDeserializeImpl(System.String s, System.Xml.Serialization.XmlSerializer xmlser, System.Action`2 OnException)
   at Klyte.Commons.Utils.XmlUtils.DefaultXmlDeserialize(System.String s, System.Action`2 OnException)
   at Klyte.Commons.Interfaces.DataExtensionBase`1.Deserialize(System.Type type, System.Byte[] data)
   at Klyte.Commons.Interfaces.DataContainer.ProcessExtension(System.Collections.Generic.Dictionary`2 instancesLegacies, System.Type type)
   at Klyte.Commons.Interfaces.DataContainer.OnLoadData()
   at SerializableDataWrapper.OnLoadData()
   at SimulationManager.LateUpdateData(UpdateMode mode, Single minProgress, Single maxProgress)
   at SimulationManager.Managers_LateUpdateData(UpdateMode mode, Single minProgress, Single maxProgress)
   at LoadingManager+<LoadSimulationData>c__IteratorB.MoveNext()
   at AsyncTask.Execute()
   at SimulationManager.SimulationStep()
   at SimulationManager.SimulationThread()

**Comment by klyte45** [comment]
Removed this alert in current version
